<a href="https://colab.research.google.com/github/Ananth-25/Deep-Learning/blob/master/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
dataset = pd.read_csv("Churn_Modelling.csv")

In [3]:
dataset.shape

(10000, 14)

In [4]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
features = dataset.iloc[:, 3:13].values
labels = dataset.iloc[:, 13].values

In [7]:
features

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [8]:
labels

array([1, 0, 1, ..., 1, 1, 0])

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [1,2])], remainder='passthrough')

features = np.array(columnTransformer.fit_transform(features), dtype = np.float32)


features = features[:, 1:] #drop the first dummy column for Geography

features = features[:, [0,1,3,4,5,6,7,8,9,10,11]] #drop the column for Gender

In [10]:

features.shape

(10000, 11)

In [11]:
features[0,:]

array([0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 6.1900000e+02,
       4.2000000e+01, 2.0000000e+00, 0.0000000e+00, 1.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0134888e+05], dtype=float32)

In [12]:
features.shape

(10000, 11)

In [13]:
from sklearn.model_selection import train_test_split
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, test_size = 0.2, random_state = 0)

In [14]:
features[0]

array([0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 6.1900000e+02,
       4.2000000e+01, 2.0000000e+00, 0.0000000e+00, 1.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0134888e+05], dtype=float32)

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
features_train = sc.fit_transform(features_train)
features_test = sc.transform(features_test)

In [16]:
features_train[0]

array([-0.56984437,  1.7430905 , -1.0916871 ,  0.16958177, -0.46460798,
        0.00666099, -1.2157176 ,  0.8095029 ,  0.64259493, -1.0322704 ,
        1.1064317 ], dtype=float32)

In [17]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [18]:
classifier = Sequential()

In [19]:
features.shape

(10000, 11)

In [20]:
#adding the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

In [21]:
# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [22]:
classifier.fit(features_train, labels_train, batch_size = 10, epochs = 10)

Epoch 1/10
800/800 [==============================] - 1s 890us/step - loss: 0.5876 - accuracy: 0.7969
Epoch 2/10
800/800 [==============================] - 1s 840us/step - loss: 0.4178 - accuracy: 0.8091
Epoch 3/10
800/800 [==============================] - 1s 844us/step - loss: 0.4064 - accuracy: 0.8123
Epoch 4/10
800/800 [==============================] - 1s 871us/step - loss: 0.3984 - accuracy: 0.8144
Epoch 5/10
800/800 [==============================] - 1s 877us/step - loss: 0.3911 - accuracy: 0.8245
Epoch 6/10
800/800 [==============================] - 1s 874us/step - loss: 0.3825 - accuracy: 0.8360
Epoch 7/10
800/800 [==============================] - 1s 843us/step - loss: 0.3869 - accuracy: 0.8269
Epoch 8/10
800/800 [==============================] - 1s 829us/step - loss: 0.3745 - accuracy: 0.8359
Epoch 9/10
800/800 [==============================] - 1s 847us/step - loss: 0.3689 - accuracy: 0.8413
Epoch 10/10
800/800 [==============================] - 1s 828us/step - loss: 0.365

In [23]:
labels_pred = classifier.predict_classes(features_test)
#labels_pred = (labels_pred > 0.5)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [24]:
labels_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int32)

In [25]:
len(labels_pred)

2000

In [26]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(labels_test, labels_pred)

In [27]:
cm

array([[1540,   55],
       [ 248,  157]])