<a href="https://colab.research.google.com/github/Ananth-25/Deep-Learning/blob/master/CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import keras

In [31]:
from keras.datasets import mnist
from keras.utils import to_categorical

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [32]:
train_images.shape

(60000, 28, 28)

In [33]:
train_images[0].shape

(28, 28)

In [34]:
train_images[10]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  42, 118,
        219, 166, 118, 118,   6,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 103, 242, 254,
        254, 254, 254, 254,  66,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [35]:
train_labels[10]

3

In [36]:
train_images = train_images.reshape((60000, 28, 28, 1))

In [37]:
train_images.shape

(60000, 28, 28, 1)

In [38]:
train_images[0]

array([[[  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0]],

       [[  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0]],

       [[  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
      

In [39]:
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28, 28, 1))
test_images = test_images.astype('float32') / 255

In [40]:
train_images[0]

array([[[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ]],

       [[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        

In [41]:
train_labels[0]

5

In [42]:
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [43]:
test_labels[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

In [45]:
print (train_labels.shape)

(60000, 10)


In [46]:
from keras import layers
from keras import models

model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(16, (5,5), activation = "relu"))
model.add(layers.MaxPooling2D((2, 2)))



In [47]:
model.add(layers.Flatten())

model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

In [48]:
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(train_images, train_labels, epochs=50, batch_size=64)

Epoch 1/50
938/938 [==============================] - 42s 44ms/step - loss: 0.2147 - accuracy: 0.9348
Epoch 2/50
938/938 [==============================] - 42s 44ms/step - loss: 0.0684 - accuracy: 0.9789
Epoch 3/50
938/938 [==============================] - 41s 44ms/step - loss: 0.0465 - accuracy: 0.9857
Epoch 4/50
938/938 [==============================] - 41s 44ms/step - loss: 0.0364 - accuracy: 0.9889
Epoch 5/50
938/938 [==============================] - 42s 44ms/step - loss: 0.0301 - accuracy: 0.9906
Epoch 6/50
938/938 [==============================] - 42s 44ms/step - loss: 0.0254 - accuracy: 0.9922
Epoch 7/50
938/938 [==============================] - 42s 44ms/step - loss: 0.0217 - accuracy: 0.9933
Epoch 8/50
938/938 [==============================] - 41s 44ms/step - loss: 0.0191 - accuracy: 0.9942
Epoch 9/50
938/938 [==============================] - 41s 44ms/step - loss: 0.0162 - accuracy: 0.9952
Epoch 10/50
938/938 [==============================] - 41s 44ms/step - loss: 0.014

In [49]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

313/313 [==============================] - 3s 8ms/step - loss: 0.1249 - accuracy: 0.9890


In [50]:
test_images[0].shape

(28, 28, 1)

In [51]:
test_acc

0.9890000224113464

In [52]:
model.layers

In [53]:
train_images[0].shape

(28, 28, 1)

In [54]:
type(train_images)

numpy.ndarray

In [55]:
test_data = train_images[10].reshape(1,28,28,1)

In [56]:
test_data.shape

(1, 28, 28, 1)

In [57]:
model.predict_classes(test_data)

array([3])

In [58]:
train_labels[10]

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [59]:
train_labels[10].argmax()

3

In [60]:
test_images.shape

(10000, 28, 28, 1)

In [61]:
test_data = test_images

In [62]:
predictions = model.predict_classes(test_data)

In [63]:
from sklearn import metrics

In [64]:
matrix = metrics.confusion_matrix(test_labels.argmax(axis=1), predictions)

In [65]:
print (matrix)

[[ 977    0    1    0    0    0    0    1    1    0]
 [   0 1125    1    1    0    0    2    3    2    1]
 [   1    0 1026    0    0    0    1    3    1    0]
 [   0    0    5 1001    0    4    0    0    0    0]
 [   0    0    1    0  972    0    0    2    0    7]
 [   1    0    1    5    0  881    1    1    1    1]
 [   7    2    3    0    3    2  940    0    1    0]
 [   0    2   10    0    0    0    0 1015    0    1]
 [   3    0    2    4    2    0    0    1  959    3]
 [   1    0    2    1    4    5    0    1    1  994]]
